version: "3.8"
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/db
  shoppingcartdb:
    container_name: shoppingcartdb
    restart: always
    ports: 
      - "6379:6379"
  identitydb:
    container_name: identitydb
    restart: always
    ports: 
      - "1433:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password12*
  orderdb:
    container_name: orderdb
    restart: always
    ports: 
      - "1444:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"