version: "3.8"
services:
  identitydb:
    image: mcr.microsoft.com/mssql/server
  catalogdb:
    image: mongo
  shoppingcartdb:
    image: redis
  orderdb:
    image: mcr.microsoft.com/mssql/server
  rabbitmq:
    image: rabbitmq:3.8.14-management
  identityserver.api:
    image: identityserver_api_image
    build:
      context: .
      dockerfile: Services/IdentityServer/Dockerfile
  catalog.api:
    image : catalog_api_image
    build:
      context: .
      dockerfile: Services/CatalogAPI/Dockerfile
  shoppingcart.api:
    image: shoppingcart_api_image
    build: 
      context: .
      dockerfile: Services/ShoppingCartAPI/Dockerfile
  order.api:
    image: order_api_image
    build:
      context: .
      dockerfile: Services/Order/Ecommerce.Services.Order.API/Dockerfile
  payment.api:
    image: payment_api_image
    build:
      context: .
      dockerfile: Services/PaymentAPI/Dockerfile
  photoservice.api:
    image: photoservice_api_image
    build:
      context: .
      dockerfile: Services/PhotoserviceAPI/Dockerfile
  gateway.api:
    image: gateway_api_image
    build: 
      context: .
      dockerfile: Gateways/Ecommerce.Gateway/Dockerfile
volumes:
  identitydb_volume:
  catalogdb_volume:
  shoppingcartdb_volume:
  orderdb_volume:
  rabbitmq_volume:
  identityserver.api_volume:
  catalog.api_volume:
  shoppingcart.api_volume:
  order.api_volume:
  payment.api_volume:
  photoservice.api_volume:
  gateway.api_volume: